name: Deploy to EC2
env:
    HOST: 'ec2-3-131-35-117.us-east-2.compute.amazonaws.com'
    SSH_KEY: 'ssh -i "react_js.pem" ubuntu@ec2-3-131-35-117.us-east-2.compute.amazonaws.com'
    
on:
 # push:
    branches:
      #- main
      - cron: "*/2 * * * *"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Copy repository to EC2
      uses: appleboy/scp-action@master
      with:
        host: $HOST
        username: ubuntu
        key: $SSH_KEY
        port: 22
        source: "."
        target: "/hello-world"

    - name: Run npm install and start
      uses: appleboy/ssh-action@master
      with:
        host: ${HOST}
        username: ubuntu
        key: ${SSH_KEY}
        port: 22
        script: |
          cd /hello-world
          npm install
          npm start
