name: Deploy to EC2

on:
 # push:
    branches:
      #- main
      - cron: "*/2 * * * *"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Copy repository to EC2
      uses: appleboy/scp-action@master
      with:
        host: ec2-3-128-229-104.us-east-2.compute.amazonaws.com
        username: ubuntu
        key: ssh -i "react_js.pem" ubuntu@ec2-3-128-229-104.us-east-2.compute.amazonaws.com
        port: 22
        source: "."
        target: "/hello-world"

    - name: Run npm install and start
      uses: appleboy/ssh-action@master
      with:
        host: ec2-3-128-229-104.us-east-2.compute.amazonaws.com
        username: ubuntu
        key: ssh -i "react_js.pem" ubuntu@ec2-3-128-229-104.us-east-2.compute.amazonaws.com
        port: 22
        script: |
          cd /path/to/your/repo
          npm install
          npm start
