name: Deploy to EC2

env:
    HOST: 'ec2-18-222-22-247.us-east-2.compute.amazonaws.com'
    SSH_KEY: 'ssh -i "react_js.pem" ubuntu@ec2-18-222-22-247.us-east-2.compute.amazonaws.com'
    USER_NAME: 'venky'
    PASSWORD: 'venky'

on:
  schedule:
    - cron: "*/2 * * * *"
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Set environment variables

      run: |
        echo "HOST=$HOST"
        echo "SSH_KEY=$SSH_KEY"
        echo "USER_NAME=$USER_NAME"
        echo "PASSWORD=$PASSWORD"

    - name: Copy repository to EC2
      uses: appleboy/scp-action@master
      with:
        host: ${{ env.HOST }}
        ssh_key: ${{ env.SSH_KEY }}
        username: ${{ env.USER_NAME }}
        password: ${{ env.PASSWORD }}
        port: 22
        source: "."
        target: "/hello-world"


    - name: Run npm install and start
      uses: appleboy/ssh-action@master
      with:
        host: ${{ env.HOST }}
        ssh_key: ${{ env.SSH_KEY }}
        username: ${{ env.USER_NAME }}
        password: ${{ env.PASSWORD }}
        port: 22
        script: |
         cd /hello-world
         npm install
         npm start
